const UNSPLASH_ACCESS_KEY = import.meta.env.VITE_UNSPLASH_ACCESS_KEY
const UNSPLASH_SECRET_KEY = import.meta.env.VITE_UNSPLASH_SECRET_KEY
const UNSPLASH_API_URL = import.meta.env.VITE_UNSPLASH_API_URL

export {
    UNSPLASH_ACCESS_KEY,
    UNSPLASH_SECRET_KEY,
    UNSPLASH_API_URL
}